const KEY='nutritrack:v1';
const foods=[
 {id:'chicken',name:'Pollo grillado',group:'protein',kcal:280,p:43,c:0,f:11},
 {id:'eggs',name:'3 huevos',group:'protein',kcal:210,p:18,c:1,f:15},
 {id:'tuna',name:'Atún al natural',group:'protein',kcal:130,p:29,c:0,f:1},
 {id:'rice',name:'Arroz integral',group:'carb',kcal:220,p:5,c:46,f:2},
 {id:'potato',name:'Papa al horno',group:'carb',kcal:160,p:4,c:36,f:0},
 {id:'lentils',name:'Lentejas',group:'legume',kcal:230,p:18,c:40,f:1},
 {id:'salad',name:'Ensalada variada',group:'vegetable',kcal:80,p:3,c:14,f:1},
 {id:'broccoli',name:'Brócoli',group:'vegetable',kcal:55,p:4,c:11,f:1},
 {id:'avocado',name:'Palta',group:'fat',kcal:120,p:2,c:6,f:11},
 {id:'olive',name:'Aceite de oliva',group:'fat',kcal:90,p:0,c:0,f:10}
];
const defaultState={profile:null,goals:null,meals:[],logs:{},customFoods:[]};
let state=load();let currentView=state.profile?'today':'onboarding';let builder={type:'Almuerzo',selected:{protein:'chicken',carb:'rice',vegetable:'salad',fat:'avocado'}};
function load(){try{return {...defaultState,...JSON.parse(localStorage.getItem(KEY))}}catch{return {...defaultState}}}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function today(){return new Date().toISOString().slice(0,10)}
function num(v){return Number(v)||0}
function bmi(){return state.profile?num(state.profile.weight)/((num(state.profile.height)/100)**2):0}
function bmr(){const p=state.profile;return p.sex==='female'?10*p.weight+6.25*p.height-5*p.age-161:10*p.weight+6.25*p.height-5*p.age+5}
function tdee(){return bmr()*({sedentary:1.2,light:1.375,moderate:1.55,high:1.725}[state.profile.activity]||1.2)}
function calculateGoals(p){const total=10*p.weight+6.25*p.height-5*p.age+(p.sex==='female'?-161:5);const t=total*({sedentary:1.2,light:1.375,moderate:1.55,high:1.725}[p.activity]||1.2);let kcal=t;if(['fat_loss','weight_loss'].includes(p.goal))kcal=t*.85;if(p.goal==='muscle_gain')kcal=t*1.08;return {calories:Math.round(kcal),protein:Math.round(p.weight*(p.goal==='muscle_gain'?1.8:1.5)),carbs:Math.round(kcal*.4/4),fat:Math.round(kcal*.3/9),water:2500,mealsPerDay:3}}
function mealsToday(){return state.meals.filter(m=>m.date===today())}
function totals(meals=mealsToday()){return meals.reduce((a,m)=>m.items.reduce((x,item)=>{const f=foods.find(y=>y.id===item.id)||state.customFoods.find(y=>y.id===item.id);if(!f)return x; x.kcal+=f.kcal*item.servings;x.p+=f.p*item.servings;x.c+=f.c*item.servings;x.f+=f.f*item.servings;return x},a),{kcal:0,p:0,c:0,f:0})}
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function shell(content){return `<div class="shell"><header class="topbar"><button class="button ghost brand" data-action="view" data-view="today">NutriTrack</button><div class="topbar-actions"><button class="button ghost" data-action="export">Exportar</button><button class="button ghost" data-action="view" data-view="profile">⚙</button></div></header>${content}<nav class="bottom-nav">${[['today','Hoy'],['meals','Comidas'],['new','+'],['evolution','Evolución'],['profile','Perfil']].map(([v,l])=>`<button class="${currentView===v?'active':''} ${v==='new'?'add':''}" data-action="view" data-view="${v}">${l}</button>`).join('')}</nav></div>`}
function render(){if(currentView==='onboarding'){document.querySelector('#app').innerHTML=onboarding();bind();return}let content=currentView==='today'?dashboard():currentView==='meals'||currentView==='new'?mealView():currentView==='evolution'?evolution():profileView();document.querySelector('#app').innerHTML=shell(content);bind()}
function onboarding(){return `<main class="onboarding"><span class="brand">NutriTrack</span><div class="card"><div class="step active" data-step="1"><span class="step-number">Paso 1 de 3</span><h1>Empecemos por conocerte</h1><p class="lead">Usaremos estos datos para calcular referencias iniciales. Podrás editarlos después.</p><div class="form-grid"><label class="field">Nombre opcional<input id="ob-name" placeholder="Tu nombre"></label><label class="field">Edad<input id="ob-age" type="number" min="13" max="100" placeholder="Ej. 35"></label><label class="field">Sexo<select id="ob-sex"><option value="male">Masculino</option><option value="female">Femenino</option><option value="other">Prefiero no indicarlo</option></select></label><label class="field">Altura en cm<input id="ob-height" type="number" placeholder="Ej. 179"></label><label class="field">Peso actual en kg<input id="ob-weight" type="number" step="0.1" placeholder="Ej. 108"></label></div></div><div class="step" data-step="2"><span class="step-number">Paso 2 de 3</span><h1>¿Cuál es tu objetivo?</h1><div class="choice-grid"><button class="choice selected" data-choice="goal" data-value="fat_loss"><strong>Bajar grasa corporal</strong><small>Priorizar composición corporal.</small></button><button class="choice" data-choice="goal" data-value="weight_loss"><strong>Bajar peso</strong><small>Buscar descenso de peso.</small></button><button class="choice" data-choice="goal" data-value="maintenance"><strong>Mantener peso</strong><small>Sostener el peso actual.</small></button><button class="choice" data-choice="goal" data-value="muscle_gain"><strong>Ganar masa muscular</strong><small>Acompañar el entrenamiento.</small></button></div></div><div class="step" data-step="3"><span class="step-number">Paso 3 de 3</span><h1>¿Cómo es tu actividad?</h1><div class="choice-grid"><button class="choice selected" data-choice="activity" data-value="sedentary"><strong>Sedentario</strong><small>Poco ejercicio habitual.</small></button><button class="choice" data-choice="activity" data-value="light"><strong>Actividad ligera</strong><small>1–2 entrenamientos.</small></button><button class="choice" data-choice="activity" data-value="moderate"><strong>Actividad moderada</strong><small>3–4 entrenamientos.</small></button><button class="choice" data-choice="activity" data-value="high"><strong>Actividad alta</strong><small>5 o más sesiones.</small></button></div></div><div class="onboarding-actions"><button class="button ghost" id="ob-back" hidden>Volver</button><button class="button primary" id="ob-next">Continuar</button></div></div></main>`}
function dashboard(){const t=totals(),g=state.goals,l=state.logs[today()]||{};const pct=Math.min(100,Math.round(t.kcal/g.calories*100));return `<section class="view active"><p class="eyebrow">${new Date().toLocaleDateString('es-AR',{weekday:'long',day:'numeric',month:'long'})}</p><h1>Buen día${state.profile.name?', '+esc(state.profile.name):''}</h1><p class="lead">Tu objetivo: ${goalLabel(state.profile.goal)}</p><div class="card hero"><span>Calorías</span><span class="value">${Math.round(t.kcal)} <small>/ ${g.calories} kcal</small></span><div class="progress"><i style="width:${pct}%"></i></div><small>${pct}% del objetivo diario</small></div><div class="grid metrics"><div class="card metric"><span class="label">Proteína</span><span class="value">${Math.round(t.p)} g</span><small>/ ${g.protein} g</small></div><div class="card metric"><span class="label">Agua</span><span class="value">${l.water||0}</span><small>/ ${g.water} ml</small></div><div class="card metric"><span class="label">Pasos</span><span class="value">${l.steps||0}</span><small>de hoy</small></div><div class="card metric"><span class="label">IMC</span><span class="value">${bmi().toFixed(1)}</span><small>referencia</small></div></div><div class="section-heading"><h2>Tus comidas</h2><button class="button ghost" data-action="view" data-view="meals">Ver todas</button></div><div class="card meal-list">${mealTypes().map(type=>{const m=mealsToday().find(x=>x.type===type);return `<button class="meal-row" data-action="${m?'open-meal':'new-meal'}" data-type="${type}"><span><strong>${type}</strong><small>${m?`${Math.round(totals([m]).kcal)} kcal`:'Sin registrar'}</small></span><strong>${m?'Ver comida':'+ Registrar'}</strong></button>`}).join('')}</div><div class="section-heading"><h2>Hábitos de hoy</h2><button class="button secondary" data-action="log-habit">Registrar</button></div><div class="card"><div class="stat-list"><div class="stat"><span>Agua</span><strong>${l.water||0} ml</strong></div><div class="stat"><span>Pasos</span><strong>${l.steps||0}</strong></div><div class="stat"><span>Peso</span><strong>${l.weight?l.weight+' kg':'Sin registrar'}</strong></div></div></div></section>`}
function mealTypes(){return ['Desayuno','Almuerzo','Merienda','Cena'].slice(0,state.goals.mealsPerDay||3)}
function mealView(){const labels={protein:'Proteína',carb:'Acompañamiento',vegetable:'Vegetales',fat:'Grasa o aderezo'};return `<section class="view active"><p class="eyebrow">Constructor de comidas</p><h1>Armá tu comida</h1><p class="lead">Elegí una opción de cada grupo y guardala en tu día.</p><div class="card"><label class="field">Tipo de comida<select id="meal-type">${mealTypes().map(x=>`<option ${builder.type===x?'selected':''}>${x}</option>`).join('')}</select></label></div>${Object.entries(labels).map(([group,label])=>`<div class="section-heading"><h2>${label}</h2></div><div class="food-grid">${foods.filter(f=>f.group===group).map(f=>`<button class="food-option ${builder.selected[group]===f.id?'selected':''}" data-action="food" data-group="${group}" data-id="${f.id}"><strong>${f.name}</strong><small>${f.kcal} kcal · ${f.p} g proteína</small></button>`).join('')}</div>`).join('')}<div class="card total"><span>Total estimado</span><strong>${builderTotals().kcal} kcal</strong><small>Proteína ${builderTotals().p} g · Carbohidratos ${builderTotals().c} g · Grasas ${builderTotals().f} g</small></div><div class="actions"><button class="button primary" data-action="save-meal">Guardar comida</button><button class="button secondary" data-action="view" data-view="today">Cancelar</button></div></section>`}
function builderTotals(){return Object.values(builder.selected).reduce((a,id)=>{const f=foods.find(x=>x.id===id);a.kcal+=f.kcal;a.p+=f.p;a.c+=f.c;a.f+=f.f;return a},{kcal:0,p:0,c:0,f:0})}
function evolution(){const entries=Object.values(state.logs).filter(x=>x.weight).slice(-7);const weights=entries.map(x=>x.weight);const avg=weights.length?weights.reduce((a,b)=>a+b,0)/weights.length:null;return `<section class="view active"><p class="eyebrow">Historial</p><h1>Evolución</h1><p class="lead">Seguimiento simple de tus tendencias, sin juicios.</p><div class="grid metrics"><div class="card metric"><span class="label">Peso promedio</span><span class="value">${avg?avg.toFixed(1)+' kg':'—'}</span><small>Últimos registros</small></div><div class="card metric"><span class="label">Comidas</span><span class="value">${state.meals.length}</span><small>registradas</small></div><div class="card metric"><span class="label">Días activos</span><span class="value">${Object.keys(state.logs).length}</span><small>con seguimiento</small></div><div class="card metric"><span class="label">Objetivo</span><span class="value">${state.goals.calories}</span><small>kcal/día</small></div></div><div class="section-heading"><h2>Peso registrado</h2></div><div class="card">${weights.length?`<div class="chart">${weights.map(w=>`<i style="height:${Math.max(8,Math.min(100,(w/Math.max(...weights))*100))}%" title="${w} kg"></i>`).join('')}</div><div class="chart-labels">${entries.map(e=>`<span>${e.date.slice(5)}</span>`).join('')}</div>`:'<div class="empty">Registrá tu peso desde Hoy para comenzar a ver tu evolución.</div>'}</div><div class="section-heading"><h2>Referencias energéticas</h2></div><div class="card table-like"><div class="row"><span>Metabolismo basal estimado</span><strong>${Math.round(bmr())} kcal</strong></div><div class="row"><span>Gasto diario estimado</span><strong>${Math.round(tdee())} kcal</strong></div><div class="row"><span>Objetivo diario</span><strong>${state.goals.calories} kcal</strong></div></div></section>`}
function profileView(){const p=state.profile;return `<section class="view active"><p class="eyebrow">Configuración</p><h1>Perfil</h1><p class="lead">Podés modificar tus referencias cuando quieras.</p><div class="card"><div class="form-grid"><label class="field">Nombre<input id="pf-name" value="${esc(p.name)}"></label><label class="field">Edad<input id="pf-age" type="number" value="${p.age}"></label><label class="field">Altura en cm<input id="pf-height" type="number" value="${p.height}"></label><label class="field">Peso actual en kg<input id="pf-weight" type="number" step="0.1" value="${p.weight}"></label><label class="field">Objetivo<select id="pf-goal">${['fat_loss','weight_loss','maintenance','muscle_gain'].map(x=>`<option value="${x}" ${p.goal===x?'selected':''}>${goalLabel(x)}</option>`).join('')}</select></label><label class="field">Actividad<select id="pf-activity">${['sedentary','light','moderate','high'].map(x=>`<option value="${x}" ${p.activity===x?'selected':''}>${activityLabel(x)}</option>`).join('')}</select></label></div><div class="actions"><button class="button primary" data-action="save-profile">Guardar cambios</button><button class="button secondary" data-action="export">Exportar datos</button><label class="button secondary">Importar datos<input id="import-data" type="file" accept="application/json" hidden></label></div></div><div class="grid two"><div class="card"><span class="eyebrow">IMC estimado</span><strong class="value">${bmi().toFixed(1)}</strong><p class="muted">Referencia general que no distingue masa muscular y grasa corporal.</p></div><div class="card"><span class="eyebrow">Objetivos diarios</span><div class="stat-list"><div class="stat"><span>Calorías</span><strong>${state.goals.calories} kcal</strong></div><div class="stat"><span>Proteína</span><strong>${state.goals.protein} g</strong></div><div class="stat"><span>Agua</span><strong>${state.goals.water} ml</strong></div></div></div></div><div class="notice">NutriTrack es una herramienta de planificación y registro. No reemplaza la consulta con profesionales de la salud.</div></section>`}
function goalLabel(x){return ({fat_loss:'bajar grasa corporal',weight_loss:'bajar peso',maintenance:'mantener peso',muscle_gain:'ganar masa muscular'})[x]||x}
function activityLabel(x){return ({sedentary:'Sedentario',light:'Actividad ligera',moderate:'Actividad moderada',high:'Actividad alta'})[x]||x}
function bind(){document.querySelectorAll('[data-action="view"]').forEach(b=>b.onclick=()=>{currentView=b.dataset.view;render()});document.querySelectorAll('[data-action="new-meal"]').forEach(b=>b.onclick=()=>{builder.type=b.dataset.type;currentView='new';render()});document.querySelectorAll('[data-action="food"]').forEach(b=>b.onclick=()=>{builder.selected[b.dataset.group]=b.dataset.id;render()});document.querySelectorAll('[data-action="open-meal"]').forEach(b=>b.onclick=()=>{const m=mealsToday().find(x=>x.type===b.dataset.type);if(m){builder.type=m.type;m.items.forEach(x=>{const f=foods.find(y=>y.id===x.id);if(f)builder.selected[f.group]=f.id});currentView='meals';render()}});const type=document.querySelector('#meal-type');if(type)type.onchange=()=>{builder.type=type.value};const saveMeal=document.querySelector('[data-action="save-meal"]');if(saveMeal)saveMeal.onclick=()=>{state.meals.push({id:crypto.randomUUID(),date:today(),type:builder.type,items:Object.values(builder.selected).map(id=>({id,servings:1}))});save();currentView='today';render()};const habit=document.querySelector('[data-action="log-habit"]');if(habit)habit.onclick=()=>{const l=state.logs[today()]||{};const water=prompt('Agua consumida en ml:',l.water||'');if(water===null)return;const steps=prompt('Pasos de hoy:',l.steps||'');const weight=prompt('Peso en kg (opcional):',l.weight||'');state.logs[today()]={...l,water:num(water),steps:num(steps),weight:weight?num(weight):l.weight};save();render()};const saveProfile=document.querySelector('[data-action="save-profile"]');if(saveProfile)saveProfile.onclick=()=>{const p={...state.profile,name:document.querySelector('#pf-name').value,age:num(document.querySelector('#pf-age').value),height:num(document.querySelector('#pf-height').value),weight:num(document.querySelector('#pf-weight').value),goal:document.querySelector('#pf-goal').value,activity:document.querySelector('#pf-activity').value};state.profile=p;state.goals=calculateGoals(p);save();render()};const exp=document.querySelectorAll('[data-action="export"]');exp.forEach(b=>b.onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.download=`nutritrack-${today()}.json`;a.click()});const imp=document.querySelector('#import-data');if(imp)imp.onchange=async e=>{try{const imported=JSON.parse(await e.target.files[0].text());if(!imported.profile||!imported.goals)throw Error();state=imported;save();render()}catch{alert('El archivo no tiene un formato válido de NutriTrack.')}};bindOnboarding()}
function bindOnboarding(){let step=1;const data={goal:'fat_loss',activity:'sedentary'};const choices=document.querySelectorAll('.choice');choices.forEach(c=>c.onclick=()=>{data[c.dataset.choice]=c.dataset.value;document.querySelectorAll(`[data-choice="${c.dataset.choice}"]`).forEach(x=>x.classList.remove('selected'));c.classList.add('selected')});const next=document.querySelector('#ob-next');if(!next)return;const show=()=>{document.querySelectorAll('.step').forEach(x=>x.classList.toggle('active',Number(x.dataset.step)===step));document.querySelector('#ob-back').hidden=step===1;next.textContent=step===3?'Comenzar':'Continuar'};next.onclick=()=>{if(step===1){data.name=document.querySelector('#ob-name').value;data.age=num(document.querySelector('#ob-age').value);data.sex=document.querySelector('#ob-sex').value;data.height=num(document.querySelector('#ob-height').value);data.weight=num(document.querySelector('#ob-weight').value);if(!data.age||!data.height||!data.weight){alert('Completá edad, altura y peso para continuar.');return}}if(step<3){step++;show()}else{state.profile={name:data.name,age:data.age,sex:data.sex,height:data.height,weight:data.weight,goal:data.goal,activity:data.activity};state.goals=calculateGoals(state.profile);save();currentView='today';render()}};document.querySelector('#ob-back').onclick=()=>{step--;show()}}
render();
